name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
      - name: Install packages
        run: npm i
      - name: Build
        run: npm run build
      - name: Setup GitHub packages auth
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - name: Deploy
        run: npm publish
