name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"
      - name: Install packages
        run: npm i
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
